### ISSUE TITLE
Android 6

### ISSUE THREAD

**Issue by alhdo** [hypeapps/Endoscope#6]
Endoscope keep crashing on android 6 with this error

FATAL EXCEPTION: Thread-7434
                                                                      Process: pl.hypeapp.endoscope, PID: 13282
                                                                      java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                          at android.os.Handler.<init>(Handler.java:200)
                                                                          at android.os.Handler.<init>(Handler.java:114)
                                                                          at android.app.Dialog.<init>(Dialog.java:130)
                                                                          at android.app.Dialog.<init>(Dialog.java:180)
                                                                          at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:43)
                                                                          at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:95)
                                                                          at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:927)
                                                                          at pl.hypeapp.endoscope.StartStreamActivity.logError(StartStreamActivity.java:224)
                                                                          at pl.hypeapp.endoscope.StartStreamActivity.onError(StartStreamActivity.java:168)
                                                                          at net.majorkernelpanic.streaming.rtsp.RtspServer.postError(RtspServer.java:300)
                                                                          at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.run(RtspServer.java:410)

**Comment by hypeapps** [comment]
@alhdo Thank you. Can you describe when you got this error? Hmm I think it may be when RTSP server got error but i don't know why yet.

**Comment by hypeapps** [comment]
@alhdo Can you change this method: 
StartStreamActivity.onError(StartStreamActivity.java:168)
`@Override
    public void onError(RtspServer server, Exception e, int error) {
        logError(e.getMessage());
}`

to

`@Override
    public void onError(RtspServer server, Exception e, int error) {
         Log.e("RTSP ERROR", e.getMessage() + " " + error);
}`

Then read the Log in android studio

**Comment by alhdo** [comment]
@hypeapps I found this error when i m trying to stream or connect to a server.

**Comment by alhdo** [comment]
When i try to act as server on android 6

08-08 14:41:09.881 23207-24241/pl.hypeapp.endoscope W/AutoFocusManager: Unexpected exception while focusing
                                                                        java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                            at android.hardware.Camera.native_autoFocus(Native Method)
                                                                            at android.hardware.Camera.autoFocus(Camera.java:1323)
                                                                            at com.google.zxing.client.android.camera.open.AutoFocusManager.start(AutoFocusManager.java:72)
                                                                            at com.google.zxing.client.android.camera.open.AutoFocusManager$AutoFocusTask.doInBackground(AutoFocusManager.java:106)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by hypeapps** [comment]
Update to version 1.3
